### ISSUE TITLE
suggested integration

### ISSUE THREAD

**Issue by italoc** [OpenGarage/homebridge-og#1]
i have modified your code and suggested to integrated this code:

with this modification if the state is the same of the request, the state don't change, is very useful if you have more than 1 opengarage, for example i have 2 garage if 1 is close and 1 is open and i have a SCENE for open and clode togheter the garage, without this modificator the state is inverted

`OpenGarageConnect.prototype.changeState = function(state, callback) {
    this.log("Set state to %s", state === Characteristic.TargetDoorState.CLOSED ? "closed" : "open");

    this.log("variable state: %s", state);
    request.get({
        url: "http://" + this.ip + "/jc"
    }, function(err, response, body) {
        if (!err && response.statusCode === 200) {
            var value = JSON.parse(body).door;
            var actualState;
            (value === 0) ? actualState = 1: actualState = 0;
            this.log("variable actualState: %s", actualState);
            this.log("variable value: %s", value);
            if (state != actualState) {
                request.get({
                    url: "http://" + this.ip + "/cc?dkey=" + this.key + "&click=1"
                }, function(err, response, body) {

                    if (!err && response.statusCode === 200) {
                        this.log("State change complete.");
                        var currentState = (state === Characteristic.TargetDoorState.CLOSED) ?
                            Characteristic.CurrentDoorState.CLOSED : Characteristic.CurrentDoorState.OPEN;

                        /** Add delay to wait for the door to finish opening or closing */
                        setTimeout(function() {
                            this.garageService.setCharacteristic(Characteristic.CurrentDoorState, currentState);
                            callback(null);
                        }.bind(this), 10000);
                    } else {
                        this.log("Error '%s' setting door state. Response: %s", err, body);
                        callback(err || new Error("Error setting door state."));
                    }
                }.bind(this));

            } else {
                var currentState = (state === Characteristic.TargetDoorState.CLOSED) ?
                    Characteristic.CurrentDoorState.CLOSED : Characteristic.CurrentDoorState.OPEN;
                setTimeout(function() {
                    this.garageService.setCharacteristic(Characteristic.CurrentDoorState, currentState);
                    callback(null);
                }.bind(this), 10000);
            }

        } else {
            this.log("Error getting state: %s", err);
            callback(err);
        }
    }.bind(this));

};`

**Comment by salbahra** [comment]
Thank you very much for this! I was having this issue and hasn’t had time to debug it or figure it out. I will try this out ASAP and incorporate this once done.

Thanks again!!

**Comment by salbahra** [comment]
I went ahead and added the code here: https://github.com/OpenGarage/homebridge-og/commit/66a8be5e9bcd210b717292d47eee435487079e2c. I used the `getState` method instead of copying the code again. Otherwise this is the same thing.

Thank you for your contribution!
