### ISSUE TITLE
homebridge-og custom polling

### ISSUE THREAD

**Issue by identd113** [OpenGarage/homebridge-og#2]
It seems the homebridge-og plugin polls for status every 4 minutes or so. This would be great if it can poll more often or have a custom poll, which could be set in the config.json
This would allow automations to fire off when the garage is opened outside of the homekit system (IE RF remote)

**Comment by mrblack7** [comment]
> This would allow automations to fire off when the garage is opened outside of the homekit system (IE RF remote)

Agree - this would be great when someone uses the RF remote or manually opens/closes the garage door.

**Comment by timcharper** [comment]
I've implemented this in my fork. Have a look:

https://github.com/timcharper/homebridge-og

**Comment by salbahra** [comment]
Added in #6 thanks to @timcharper
