### ISSUE TITLE
Incorrect notifications/responses

### ISSUE THREAD

**Issue by mbdmbd** [OpenGarage/homebridge-og#3]
Hi,

When I tell Siri to open my garage door, I'll get two notifications from the Home.app on my phone:

> * HOME
> MyHome
> Garage was opened.

then immediately after:

> * HOME
> MyHome
> Garage was closed.

When I then close the garage door I get one more notification, but instead of saying it's closed, it says it's open;

> * HOME
> MyHome
> Garage was opened.

Is this typical/expected behaviour?

![img_0799](https://user-images.githubusercontent.com/12741220/38408618-a2c4bf80-39c1-11e8-89c7-0b6ef646f7d2.jpg)

**Comment by mbdmbd** [comment]
Additionally, Siri will sometimes say she was unable to perform the action, when it did indeed happen:

Phone screen:
![img_0800](https://user-images.githubusercontent.com/12741220/38408788-6482ec64-39c2-11e8-91dc-9de3e1271069.PNG)

OpenDoor log:
=-=-=-=-=
Opened | 06/04/2018, 5:44:04 pm | 19 cm
=-=-=-=-=

**Comment by timcharper** [comment]
Try my fork and see if you have the same issue. I've refined the logic for how open / close transitions happen.

**Comment by salbahra** [comment]
Should be fixed in #6
