### ISSUE TITLE
Scenes that include shutting the garage door just trigger regardless

### ISSUE THREAD

**Issue by timcharper** [OpenGarage/homebridge-og#4]
Version 2.1.0 installed from npm

Steps to reproduce:

1. Create a scene that says your garage door should be closed
2. Make sure your garage door is closed, and the state shows up as such in Home
3. Trigger your scene
4. Watch in amazement as your garage door opens

**Comment by timcharper** [comment]
(I'm not sure if this is a Homekit bug but I suspect it is sending the target door state even though the door is already closed, and the plugin is failing to realize that the target door state matches the current state and therefore no action should take place)

**Comment by timcharper** [comment]
Is this the fix for this issue? https://github.com/OpenGarage/homebridge-og/commit/66a8be5e9bcd210b717292d47eee435487079e2c 

Looks unreleased.

**Comment by timcharper** [comment]
I've confirmed this does not happen in my fork

https://github.com/timcharper/homebridge-og

**Comment by salbahra** [comment]
Merged #6 which fixes this issue.
